## Packages
suppressMessages(library(dplyr))

## Function to write a FASTA file from a data frame
writeFasta <- function(data, filename) {
  # Initialize an empty vector to store FASTA lines
  fastaLines <- c()
  
  # Loop through each row of the data frame
  for (rowNum in 1:nrow(data)) {
    # Create a FASTA header line using the "Sample" column
    header <- paste0(">", data[rowNum, "asv_seq"])
    # Add the header line to fastaLines vector
    fastaLines <- c(fastaLines, header)
    
    # Get the sequence from the "seq" column
    sequence <- data[rowNum, "asv_seq"]
    # Add the sequence line to fastaLines vector
    fastaLines <- c(fastaLines, sequence)
  }
  
  # Open a file connection to the specified filename
  fileConn <- file(filename)
  
  # Write fastaLines to the file connection
  writeLines(fastaLines, fileConn)
  
  # Close the file connection
  close(fileConn)
}




# Read in the output table generated by vsearch and assign column names
output_table_GTDB <- read.table(file= snakemake@input[["GTDB_file"]], sep = '\t', header = F)

# Create a vector of column names for the output table
names <- c("asv_seq", "taxonomy", "identity")

colnames(output_table_GTDB) <- names

# Joining the GTDB output and the first 3 columns of the annotation file 
annotation_table <- read.table(file= snakemake@input[["annotation"]], sep = ',', header = T)
annotation_table<-annotation_table[,1:3]

df<-data.frame(annotation_table) %>% left_join(output_table_GTDB,by="asv_seq",multiple = "all")

write.table(df,file=snakemake@output[["Combined"]], row.names= F, sep= "\t")


# Create a new data frame of sequences with no hits in the output table, based on the 'Taxa' column being NA

no_hits <- data.frame(df[,1:3]) %>% filter(is.na(df[,"taxonomy"]))


# Write the sequences with no hits to a new FASTA file named 'no_hits_GTDB.fasta'
writeFasta(no_hits, snakemake@output[["GTDB_noHIT"]])




