community_counts <- list(
  ATCC_skin = data.frame(Taxa = c("Acinetobacter_johnsonii", "Corynebacterium_striatum",
                                  "Cutibacterium_acnes", "Micrococcus_luteus",
                                  "Staphylococcus_epidermidis", "Streptococcus_mitis"),
                         Expected = c(16.7, 16.7, 16.7, 16.7, 16.7, 16.7)),
  ATCC_vagina = data.frame(Taxa = c("Gardnerella_vaginalis", "Lactobacillus_gasseri",
                                    "Lactobacillus_jensenii", "Mycoplasma_hominis",
                                    "Prevotella_bivia", "Streptococcus_agalactiae"), 
                           Expected = c(16.7, 16.7, 16.7, 16.7, 16.7, 16.7)),
  zymo_DNA_ST = data.frame(Taxa = c("Pseudomonas_aeruginosa", "Escherichia_coli",
                             "Salmonella_enterica", "Lactobacillus_fermentum",
                             "Enterococcus_faecalis", "Staphylococcus_aureus",
                             "Listeria_monocytogenes", "Bacillus_subtilis",
                             "Saccharomyces_cerevisiae","Cryptococcus_neoformans"),
                    Expected = c(4.2, 10.1, 10.4, 18.4, 9.9, 15.5, 14.1, 17.4,0,0)),
  zymo_gut = data.frame(Taxa = c("Faecalibacterium_prausnitzii", "Veillonella_rogosae",
                                 "Roseburia_hominis", "Bacteroides_fragilis",
                                 "Prevotella_corporis", "Bifidobacterium_adolescentis",
                                 "Fusobacterium_nucleatum", "Lactobacillus_fermentum",
                                 "Clostridioides_difficille", "Akkermansia_muciniphila",
                                 "Methanobrevibacter_smithii", "Salmonella_enterica",
                                 "Enterococcus_faecalis", "Clostridium_perfringens",
                                 "Escherichia_coli_JM109", "Escherichia_coli_B3008",
                                 "Escherichia_coli_B2207", "Escherichia_coli_B766",
                                 "Escherichia_coli_B1109","Candida_albicans","Saccharomyces_cerevisiae"),
                        Expected = c(14, 14, 14, 14, 6, 6, 6, 6, 1.5, 1.5, 0.1,0.01, 0.001,0.0001, 2.8, 2.8, 2.8,2.8, 2.8,1.5,1.4)))
